# docker-compose.yml
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Expose Vite's default development server port
    volumes:
      - ./src:/app/src  # Mounts the src folder for live reloading
      - ./public:/app/public  # Mounts the public folder for live reloading
      - /app/node_modules  # Keeps node_modules inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures hot reloading works in Docker
