services:
  backend:
    container_name: keelcompass-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - IS_DOCKER=true
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  frontend:
    container_name: keelcompass-frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
